### ISSUE TITLE
Playback Controls Missing

### ISSUE THREAD

**Issue by acass91** [googlesamples/androidtv-sample-inputs#11]
When I run this app. on an Android N emulator, I can channel change, but I cannot pause, rewind, or fast-forward any video. I can navigate the menu using the d-pad, but nothing happens when any of the playback control buttons are pressed. 

From https://source.android.com/devices/tv/, "For TV Inputs that support time shifting, the TV App needs to display playback controls". Do the sample inputs support time shifting?

**Comment by Fleker** [comment]
The sample inputs app currently does not support time shifting.

**Comment by Fleker** [comment]
The sample has since been added to support time-shifting
