### ISSUE TITLE
Release TV Input Framework Companion Library as library

### ISSUE THREAD

**Issue by mkjensen** [googlesamples/androidtv-sample-inputs#12]
The TV Input Framework Companion Library mentioned at http://android-developers.blogspot.dk/2016/11/adding-tv-channels-to-your-app-with-the-tif-companion-library.html and available at https://github.com/googlesamples/androidtv-sample-inputs/tree/master/library is currently usable by copying the code to other projects.

Wouldn't it be nicer if the The TV Input Framework Companion Library was actually released as a library such that it could simply be included as a dependency?

**Comment by Fleker** [comment]
I agree. It definitely should be a library so it's easy for existing apps
to add the features with less work.

**Comment by SteinerOk** [comment]
I added it to Bintray, you can add to Gradle build file:
`compile 'com.google.android.media.tv:companionlibrary:1.0.1'`

**Comment by smishra2** [comment]
We have plans to publish the library on JCenter soon. This issue will be updated when that is done.

**Comment by smishra2** [comment]
Hey folks, please use the following Gradle dependency from JCenter: 
`compile 'com.google.android.libraries.tv:companionlibrary:0.1'`

**Comment by Fleker** [comment]
It's great to see an official JCenter dependency, although this should probably be added to the README for new developers to quickly learn how to get started.

**Comment by smishra2** [comment]
Good idea, @Fleker. Done.

**Comment by JJSarrasin** [comment]
And it should also be updated, it has some reference to old libraries like  com.google.android.gms:play-services-basement:8.4.0

And it conflicts depending on your project configuration and gradle version..

**Comment by vincbeaulieu** [comment]
with the latest android studio I can't manage to implement the library from gradle and when I import manually the library it doesn't want to recognized it and a bunch of error shows...
How can I overcome this problem?

**Comment by JessAA** [comment]
Hey 
jCenter will be shutdown soon. Does this library `com.google.android.libraries.tv:companionlibrary` exist in other repository such as mavenCentral? Or is it in process of migration to another repository?

Thanks 🙏

**Comment by prakash-khandelwal** [comment]
Hi.. How to use this library now? I'm facing below issue from past couple of days in a new setup-

Failed to resolve: com.google.android.libraries.tv:companionlibrary:0.4.1
<a href="open.dependency.in.project.structure">[Show in Project Structure dialog](https://github.com/googlesamples/androidtv-sample-inputs/issues/open.dependency.in.project.structure)</a>
Affected Modules: <a href="openFile:D:/Projects/Workspace/PraxoPlayer/[app](openfile:D:/Projects/Workspace/PraxoPlayer/app/build.gradle.kts)/build.gradle.kts">app</a>
<a href="explain.issue">[>> Ask Gemini](https://github.com/googlesamples/androidtv-sample-inputs/issues/explain.issue)</a>

![image](https://github.com/user-attachments/assets/491bb038-fcaa-4301-8319-28b0e58b703c)

**Comment by aapunain** [comment]
any fix for this ?
still getting - Could not find com.google.android.libraries.tv:companionlibrary:0.4.1.
