### ISSUE TITLE
Playback restarts when EPG is updated

### ISSUE THREAD

**Issue by mkjensen** [googlesamples/androidtv-sample-inputs#19]
When you are watching a program and EPG is updated, then playback restarts. The experience is a bit annoying because the stream may revert to lower quality and buffer until it switches back to the (higher) quality before the restart. Also, it may happen that you get to rewatch a couple of seconds.

A workaround is to ensure that EPG updates occur less frequently but that may conflict with always having the latest EPG information.

I have not had time to investigate further (I just discovered the restarts when watching and noticed that they match with the EPG update timing) but at least now it's tracked as an issue here.

This has (so far) been tested with `com.google.android.media.tv:companionlibrary:1.0.1`.

**Comment by Fleker** [comment]
Yes this sounds annoying. Is the TV input service receiving a broadcast
that's causing it to reload the programs?

**Comment by mkjensen** [comment]
I had a little time to look at this again. I'm now using `com.google.android.libraries.tv:companionlibrary:0.2`.

While EPG updates may cause an issue when occurring while watching (I really didn't investigate this completely yet), it turns out that what has been annoying me is that when I'm watching a program and it ends (and the next program begins), there is a small hiccup. I think it is because the system is starting playback of the next program. However, in my case the next program is supplied by the same live stream (the same video URL) so really it is not necessary to start playing a new program. I guess I can easily fix this by, in my implementation of `com.google.android.media.tv.companionlibrary.BaseTvInputService.Session#onPlayProgram` checking if the program to be played has the same video URL as what is currently playing and if it has then do nothing.

By the way, this has been my only issues with the library (and it may turn out that I'm at fault) that otherwise has made it very easy to implement channels for Android TV. So thank you for providing the library!

**Comment by Fleker** [comment]
Feel free to do a PR if you find any ways to improve it. I'd like to see
what kind of projects you're using it in.

**Comment by mkjensen** [comment]
Since making the change mentioned in my previous comment I have been using my app without any issues. So my problem was my own fault and unrelated to the library. Sorry for the trouble and thanks again for the library!

I'm using the library for https://github.com/mkjensen/tv which enables me to view some Danish TV channels on my NVIDIA Shield TV. I cancelled my cable subscription since the Danish Broadcasting Corporation streams the channels for free(*) via the internet.

(*) You have to pay a special "media licence" / tax but you have to pay that regardless of how you watch the content (you even have to pay just for having the possibility to watch).
