### ISSUE TITLE
TvInputService.Session KeyEvent.Callbacks Never Called

### ISSUE THREAD

**Issue by aschober** [googlesamples/androidtv-sample-inputs#2]
It appears the ```KeyEvent.Callbacks``` (```onKeyDown```, ```onKeyUp```, etc) defined in ```TvInputService.Session``` never get called.

I've tried modifying ```RichTvInputService``` to override these methods and never see them fired.

The window that holds ```mOverlayView``` appears never to get focus even after removing the ```FLAG_NOT_FOCUSABLE``` flag so no way to hear ```KeyEvents``` via the ```mOverlayView``` either.

It appears there is supposed to be a way to capture key events in the ```TvInputService``` before the key events are handled by the application as the ```onKeyDown```, ```onKeyUp```, ```onKeyLongPress``` are defined in ```TvInputServices.Session```. Is this just not implemented yet?

**Comment by aschober** [comment]
Bump.
Any feedback available?

**Comment by aschober** [comment]
Issue continues to appear in Android 5.1.0 (LMY47D) release for Nexus Player.

**Comment by ph0b** [comment]
Unfortunately, you should be able to capture key events only if your hap is signatureOrSystem.

At least according to https://source.android.com/devices/tv/#permissions :
"Only signatureOrSystem TV Inputs and TV App have full access to the TV Provider database and are able to receive KeyEvents."

**Comment by shawngit** [comment]
Yes indeed only apps with system privilege can have full access to key events.  :-)

**Comment by aaleemakhund** [comment]
any update on this? I have system app, but its still not working.
