### ISSUE TITLE
Where is code for Companion Library 0.4.1?

### ISSUE THREAD

**Issue by stquinn** [googlesamples/androidtv-sample-inputs#33]
I can see that there is a new version(0.4.1)[1] of the companion library in bintray, and it is referenced in several bug reports on this repo.

I cannot see where this code is checked in?  Has the branch been deleted by accident?  Or has the repo moved to another location that I am just not seeing?

[1] - https://bintray.com/google/tif-companion/tif-companion/0.4.1

**Comment by stari4ek** [comment]
The question is still valid

**Comment by Fleker** [comment]
I'll get to this after returning from the holidays

**Comment by Fleker** [comment]
The project has been updated to the latest revision.
