### ISSUE TITLE
How to use EpgJobService in companionlibrary 0.4.1 ?

### ISSUE THREAD

**Issue by phycon** [googlesamples/androidtv-sample-inputs#34]
Dear Sir

I want to upgrade sample-inputs with companionlibrary 0.4.1 version.
How to use com.google.android.media.tv.companionlibrary.EpgSyncJobService in companionlibrary 0.4.1 ?

**Comment by Fleker** [comment]
It should be the same as [the sample project](https://github.com/googlesamples/androidtv-sample-inputs/tree/master/app) in this repo and in [the documentation](https://developer.android.com/training/tv/tif/tvinput).
