### ISSUE TITLE
how to compile it on android studio 3.1.4 

### ISSUE THREAD

**Issue by AlbertEinsteinGlitchPoint** [googlesamples/androidtv-sample-inputs#38]
Hi guys 

i am having alot of erros trying to compile this on the new android studio 3.1.4 with myssing files , and sync projects..

can anyone confirm this can be compiled on new android studio 3.1.4 with sdk 27

**Comment by Fleker** [comment]
Yeah there was a compilation issue I reproduced on a clean pull. This has been fixed.
