### ISSUE TITLE
How to add custom categories to group the channels in program guide?

### ISSUE THREAD

**Issue by aisbd** [googlesamples/androidtv-sample-inputs#40]
I've seen the programs have genre feature and its limited to some genres from TvContract.Programs.Genres . But is there any way that I can group channels without program data by categories like usa, uk etc.

I have some channels that don't have program data. I want to show them on the tif program guide and group them by my custom categories.

Please some help me how could I achieved this. 

Thanks

**Comment by Fleker** [comment]
You cannot provide custom genres in the TV app.
