### ISSUE TITLE
App just stops after first dialog (Nexus Player)

### ISSUE THREAD

**Issue by DavidMihola** [googlesamples/androidtv-sample-inputs#5]
I tried starting the app on a Nexus Player. The only thing I get to see is a dialog with the text

"Setup Simple Input. Do you want to register detected channels?"

And then, whether I click "OK" or "Cancel" the app just stops.

Here is the logcat output as captured with pidcat.py:

    Process com.example.android.sampletvinput created for activity com.example.android.sampletvinput/.simple.SimpleTvInputSetupActivity
                            PID: 16685   UID:    GIDs: 

                    art  E  Failed writing handshake bytes (-1 of 14): Broken pipe
                         I  Debugger is no longer active
         OpenGLRenderer  D  Use EGL_SWAP_BEHAVIOR_PRESERVED: true
                 linker  W  gralloc.moorefield.so: unused DT entry: type 0x1d arg 0x8d2
                  Atlas  D  Validating map...
         OpenGLRenderer  I  Initialized EGL, version 1.4
                         W  Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
                 linker  W  libpvrcpt.so: unused DT entry: type 0x1d arg 0xe97
         OpenGLRenderer  D  Enabling debug mode 0

                            Process com.example.android.sampletvinput (PID: 16685) ended

**Comment by ryanseys** [comment]
This is likely an obsolete issue. The sample works fine on my Nexus Player. We've removed the simple input as well, as our best practices are that videos are loaded from an external source rather than from a local file. Let me know if you're still having issues.
