### ISSUE TITLE
Multitrack support 

### ISSUE THREAD

**Issue by stpolwawa** [googlesamples/androidtv-sample-inputs#6]
Hello All,
I’m trying to adopt that code to my project. My development device is ADT-1 Google’s box.
Within 2 month I managed to port it to Exoplayer 1.4.2 and then to 1.5.0 version.
The first port has brought many changes in the code while the second one was most painful since the code was almost similar but did not work. It turned out that reverting commend call sequence solved my pain.
Since Exo 1.5.0 supports multitrack I wanted to implement it in my project. 
Question is where to define the tracks. 
I put the fake data in mTvTracks in the “prepare” method in TvInputPlayer since this method calls prepareInternal and one calls onPrepared and finally onPreapred in RichTvinputService contains notifyTracksChanged(tracks) and notifyTrackSelected(). (BTW the track data was fake since that was too early to get tracks data from mPlayer which are set when the first frame is drawn. So this is another issue where to set tracks using latest Exopalyer). But the main point here is that after setting tracks and calling onPrepared, the “prepare” method is called once again, many times. So playback brakes for each call and finally the screen is black.
According this (https://developer.android.com/training/tv/tif/ui.html) the notifyTracksChanged() can be called whenever there is a change in track information. But it recursively invokes the player start.
Can you comment/fix on this.
Regards,
Paul

**Comment by ryanseys** [comment]
I've updated this sample to use the latest ExoPlayer (1.5.6) so give multitrack another try. Let me know if you have any issues.
