### ISSUE TITLE
App installed fine but on launching it takes me to ReadMe file 

### ISSUE THREAD

**Issue by adetheprince** [googlesamples/androidtv-sample-inputs#8]
Hi there
I am trying to make this work with android device sdk 19, (not TV), the app installed fine but funny I am getting the Read Me file on this source on launching the app.
I thought I will get the video to play from the file RichTvInputService.
How do I get the  sample channels to show and play, and finally which file contain the links for mp4 or m3u8?
Many thanks.

**Comment by ryanseys** [comment]
This will only work on TV as it uses the TV input framework to expose channels. Seeing the README when you open the app is expected. If you want to play a generic video, check out ExoPlayer: https://github.com/google/ExoPlayer

**Comment by adetheprince** [comment]
"Seeing the README when you open the app is expected".
So this means the app is working with my device? then again how can we play launch the sample links direct? I also tested the Exoplayer already, so I was just wondering if this a full IPTV player.
Thanks for your reply.

**Comment by ryanseys** [comment]
It means that the activity is working. I wouldn't expect your Android phone to run the TV Input Service given it's an Android TV specific feature. This exposes some channels in the built-in Live Channels app on TV. If you're interested in creating an Android TV app for TV that allows you to play videos, check out the Leanback sample: https://github.com/googlesamples/androidtv-Leanback

**Comment by adetheprince** [comment]
Thanks for your reply sir!
Actually my Android device is not a phone but its an Android TV set box that is running android 4.4 
(MX Android Tv Box, plenty on Ebay and Amazon)
and it installed any apk without issues, I thought it would work with your code, but as you said this only work with Android Tv like Samsung smart Tv for now.
Please see if you can add this feature on the next release as its similar to any android device.
Many thanks for your info.

**Comment by ryanseys** [comment]
If your hardware doesn't support it, you'll have to wait for whoever made the hardware to update their software. If you want an officially supported Android TV device, check out the Nexus Player or NVidia Shield.
