### ISSUE TITLE
Update sample app to use recording APIs

### ISSUE THREAD

**Issue by Fleker** [googlesamples/androidtv-sample-inputs#9]
The Android N preview includes APIs for recording channels and programs through Live Channels, although there's still a bit of uncertainty about how exactly these APIs should be implemented. This example app should implement these APIs so other developers can see how it should be done.

http://developer.android.com/preview/features/tv-recording-api.html

It may make sense to put the N preview code in a separate branch so as not to confuse other developers.

**Comment by ryanseys** [comment]
Thanks Nick, we agree this should be implemented and put in a separate branch (like PIP is currently done with the Leanback sample). Right now developers don't have a clear way to test this functionality with the Live Channels app, but we're working on this. 😄

**Comment by Fleker** [comment]
Great. Let me know when you do and I'll incorporate it into my apps as well.
